### PR TITLE
Normalized +x and new binaries for rk3399/rk3399pro

### PR DESCRIPTION
**Pull request by psztoch**

### CODE REVIEW

**Comment by igorpecovnik** [comment]
Those blobs needs to be tested on all affected boards before merge - we have seen regressions on some boards in the past. IMO conditonally we can merged after 21.05 is released.

**Comment by psztoch** [comment]
But it is repo with binaries only. If you do not merge, then it won't be tested...
New versions are in new files...

**Comment by igorpecovnik** [comment]
It depends who will do this testing :) If we give users to test and some boards fails ... some people won't be happy and this is also a step back for us. We try to provide tested builds. Our test farm is not big and things are not fully automatized yet.

> New versions are in new files...

Experiences tells, that we can't blindly trust Rockchip, nor Linux, nor u-boot upstream changes. Since last week we only merge tested bug fixes. Here we know nothing and we don't know what was changed.

I am also on vacations for a week, to recover ...

**Comment by psztoch** [comment]
I have the impression that we did not understand each other.
After initial testing, I added binary blobs.
I don't push any changes to armbian / builder in area of using new blobs.
Please approve the local pull request (rkbin) so then we can continue to test it safely (on our local builder repo).

**Pull request merged**
